{
  "openapi": "3.0.0",
  "info": {
    "title": "PHP REST API Pro",
    "version": "1.0.0",
    "description": "API de usuários desenvolvida em PHP",
    "contact": {
      "name": "XxZeroxX",
      "url": "https://github.com/AntonioCarioca"
    }
  },
  "servers": [
    {
      "url": "https://phpapipro.dev.localhost/api"
    }
  ],
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "tags": [
    {
      "name": "Users",
      "description": "Gerenciamento de usuários"
    },
    {
      "name": "Auth",
      "description": "🔐 Autenticação e geração de JWT"
    }
  ],
  "paths": {
    "/users": {
      "get": {
        "tags": ["Users"],
        "summary": "Listar usuários",
        "description": "Retorna todos os usuários",
        "responses": {
          "200": {
            "description": "Lista de usuários",
            "content": {
              "application/json": {
                "example":
                  {
                    "success": true,
                    "data": [
                      {
                        "id": 1,
                        "name": "Antonio",
                        "email": "antonio@email.com"
                      }
                    ]
                  }
              }
            }
          },
          "401": {
            "description": "Não autorizado",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "Token inválido, ausente ou expirado."
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["Users"],
        "summary": "Criar usuário",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserCreate"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Usuário criado",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "message": "Usuário criado com sucesso.",
                  "data": {
                    "name": "teste",
                    "email": "teste@email.com",
                    "password": "teste123"
                  }
                }
              }
            }
          },
          "422": {
            "description": "Dados invalidos",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "Dados inválidos."
                }
              }
            }
          },
          "401": {
            "description": "Não autorizado",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "Token inválido, ausente ou expirado."
                }
              }
            }
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "tags": ["Users"],
        "summary": "Buscar usuário por ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": { "type": "integer" }
          }
        ],
        "responses": {
          "200": {
            "description": "Usuário encontrado",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "data": {
                    "id": 1,
                    "name": "example",
                    "email": "example@email.com"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Usuário não encontrado",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "Usuário não encontrado."
                }
              }
            }
          },
          "401": {
            "description": "Não autorizado",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "Token inválido, ausente ou expirado."
                }
              }
            }
          }          
        }
      },
      "put": {
        "tags": ["Users"],
        "summary": "Atualizar usuário",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": { "type": "integer" }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserUpdate"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Usuário atualizado",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "message": "Usuário atualizado com sucesso.",
                  "data": {
                    "id": 1,
                    "name": "update",
                    "email": "update@email.com"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Usuário não encontrado",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "Usuário não encontrado."
                }
              }
            }
          },
          "422": {
            "description": "Dados inválidos",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "Dados inválidos."
                }
              }
            }
          },
          "401": {
            "description": "Não autorizado",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "Token inválido, ausente ou expirado."
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Users"],
        "summary": "Deletar usuário",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": { "type": "integer" }
          }
        ],
        "responses": {
          "200": {
            "description": "Usuário Deletado",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "message": "Usuário removido com sucesso.",
                }
              }
            }
          },
          "404": {
            "description": "Usuário não encontrado",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "Usuário não encontrado."
                }
              }
            }
          },
          "401": {
            "description": "Não autorizado",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "Token inválido, ausente ou expirado."
                }
              }
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "tags": ["Auth"],
        "summary": "Login do usuário",
        "description": "Retorna um JWT válido",
        "security": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Login"
              },
              "example": {
                "email": "admin@email.com",
                "password": "123456"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Login realizado",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "token": "eyJhbGciOiJIUzI1NiIs...",
                  "user": {
                    "id": 1,
                    "name": "Demo User",
                    "email": "demo@api.com"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Credenciais inválidas",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "Credenciais inválidas"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "UserCreate": {
        "type": "object",
        "required": ["name", "email", "password"],
        "properties": {
          "name": { "type": "string" },
          "email": { "type": "string" },
          "password": { "type": "string" }
        }
      },
      "UserUpdate": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "email": { "type": "string" }
        }
      },
      "Login": {
        "type": "object",
        "required": ["name", "password"],
        "properties": {
          "name": { "type": "string" },
          "password": { "type": "string" }
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "description": "Insira seu JWT"
      }
    }
  }
}